SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `generatordb`.`personage` ADD COLUMN `generated` TINYINT(1) NULL DEFAULT NULL  AFTER `age` , CHANGE COLUMN `race_id` `race_id` INT(11) NOT NULL  AFTER `id` ;

ALTER TABLE `generatordb`.`personage_has_attribute` ADD COLUMN `priority` VARCHAR(45) NULL DEFAULT NULL  AFTER `current_value` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
